name: compress-and-copy-to-S3
on: [push]
jobs:
  compress-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: tar -czvf archive-to-s3.tar.gz files-to-compress/
      - uses: actions/checkout@master
      - name: Upload binary to S3 bucket
      - uses: tpaschalis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          FILE: ./archive-to-s3.tar.gz
          AWS_REGION: 'eu-central-1'
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}